type God {
  _id: ID
  """
  Nome do Deus
  """
  name: String!
  """
  Portfólio do Deus
  """
  portfolio: [String]
  """
  Descrição do Deus
  """
  description: String
  """
  Obrigações e Restrições do Deus
  """
  obligations: String
  """
  Crenças e Objetivos do Deus
  """
  creeds: String
  """
  Arma favorita do Deus
  """
  favoriteWeapon: String
  """
  Símbolo sagrado do Deus
  """
  holySymbol: String
  """
  Tipo de energia do Deus
  """
  energyType: String
  """
  Classes permitidas do Deus
  """
  approvedClassIds: [ID]
  """
  Raças permitidas do Deus
  """
  approvedRaceIds: [ID]
  """
  Poderes concedidos do Deus
  """
  grantedPowerIds: [ID]
}

input GodInput {
  name: String
  description: String
  portfolio: [String]
  obligations: String
  creeds: String
  favoriteWeapon: String
  holySymbol: String
  energyType: String
  approvedClassIds: [ID]
  approvedRaceIds: [ID]
  grantedPowerIds: [ID]
}

type Query {
  gods: [God]!
}

type Mutation {
  createGod(data: GodInput): God
  updateGod(godId: ID, data: GodInput): God
}
