type Character {
  _id: ID!
  """
  Nome do personagem
  """
  name: String
  """
  ID - Jogador
  """
  userId: ID
  """
  Jogador
  """
  user: User
  """
  Atributo Força
  """
  str: Int
  """
  Atributo Destreza
  """
  dex: Int
  """
  Atributo Constituição
  """
  con: Int
  """
  Atributo Inteligência
  """
  int: Int
  """
  Atributo Sabedoria
  """
  wis: Int
  """
  Atributo Carisma
  """
  car: Int
  """
  Pontos de vida máximos
  """
  pv: Int
  """
  Pontos de vida atuais
  """
  currPv: Int
  """
  Pontos de mana máximos
  """
  pm: Int
  """
  Pontos de mana atuais
  """
  currPm: Int
  """
  Pontos de experiência atuais
  """
  exp: Int
  """
  ID - Devoto de: Deus
  """
  devoutGodId: ID
  """
  Devoto de: Deus
  """
  devoutGod: God
  """
  ID - origem do personagem
  """
  originId: ID
  """
  Origem do personagem
  """
  origin: Origin
}

input InitialCharacterInput {
  name: String
  isPublic: Boolean
}

input AtributeInput {
  str: Int
  dex: Int
  con: Int
  int: Int
  wis: Int
  car: Int
}

input StatusInput {
  pv: Int
  currPv: Int
  pm: Int
  currPm: Int
  exp: Int
  isPublic: Boolean
}

type Query {
  getPlayerCharacters(userId: ID): [Character]!
  getPublicCharacters: [Character]!
  getCharacter(characterId: ID): Character
}

type Mutation {
  newCharacter(userId: ID!, data: InitialCharacterInput): Character
  updateAttributes(characterId: ID!, data: AtributeInput): Character
  updateStatus(characterId: ID!, data: StatusInput): Character
  updateDevoutGod(characterId: ID!, godId: ID): Character
  deleteCharacter(characterId: ID): Character
}
